### ISSUE TITLE
部分小韵的编码缺失韵部地位字段

### ISSUE THREAD

**Issue by JwietPuj-Drin** [untunt/qieyun-rime-table#1]
```
PS C:\qieyun-rime-table-main> python yuntu_gen_run.py
120 差 初開三支平 => 初開二佳平
130 釃 生開三支平 => 生開二佳平
140 齜 莊開三支平 => 莊開二佳平
143 齹 崇開三支平 => 崇開二佳平
607 潺 崇開三仙平 => 崇開二山平
633 恮 莊合三仙平 => 莊合二山平
634 栓 生合三仙平 => 生合二山平
802 爹 端開三麻平 => 異常 ('端', '開', '四', None, '', '平')
884 生 生開三庚平 => 生開二庚平
1037 鏐 來三幽平 => 來三尤平
1121 襳 生開三鹽平 => 生開二咸平
1224 躧 生開三支上 => 生開二佳上
1236 㧗 莊開三支上 => 莊開二佳上
1423a 箉 定開二佳上 => 異常 ('定', '開', '四', None, '', '上')
1454 茝 昌開三廢上 => 異常 ('清', '開', '三', None, '', '上')
1497 濜 崇開三眞上 => 崇開三臻上
1509 𧤛 莊開三欣上 => 莊開三臻上
1512 齔 初開三欣上 => 初開三臻上
1653 撰 崇合三仙上 => 崇合二山上
1663 棧 崇開三仙上 => 崇開二山上
1830 𩦠 並三陽上 => 異常 ('並', '開', '三', None, '', '上')
1859 省 生開三庚上 => 生開二庚上
2091 𠑆 徹開三嚴上 => 徹開三鹽上
2179 屣 生開三支去 => 生開二佳去
2194 𧙁 莊開三支去 => 莊開二佳去
2389 𠻜 生合三祭去 => 生合二皆去
2395 㯔 初合三祭去 => 初合二皆去
2400 㡜 生開三祭去 => 生開二皆去
2567 櫬 初開三眞去 => 初開三臻去
2607 𣀔 初合三元去 => 初合二山去
2736 𨏉 生合三仙去 => 生合二山去
2741 䉵 崇合三仙去 => 崇合二山去
2742 孨 莊合三仙去 => 莊合二山去
2959 㵾 初開三庚去 => 初開二庚去
2964 生 生開三庚去 => 生開二庚去
3302 㓼 初開三眞入 => 初開三臻入
3312 𪗨 崇開三眞入 => 崇開三臻入
3520 㕞 生合三仙入 => 生合二山入
3527 茁 莊合三仙入 => 莊合二山入
3530 榝 生開三仙入 => 生開二山入
3535 㔍 初合三仙入 => 初合二山入
3539 𨵊 崇開三仙入 => 崇開二山入
3602 𡩡 生開三庚入 => 生開二庚入
3603 柵 初開三庚入 => 初開二庚入
3827 萐 生開三鹽入 => 生開二咸入
3867 殜 以開三嚴入 => 以開三鹽入
3873 䎎 孃開三嚴入 => 孃開三鹽入
3874 𦑣 徹開三嚴入 => 徹開三鹽入
Traceback (most recent call last):
  File "C:\qieyun-rime-table-main\yuntu_gen_run.py", line 5, in <module>
    讀取文件('diwei_added.txt')
  File "C:\qieyun-rime-table-main\yuntu_gen.py", line 458, in 讀取文件
    插入小韻(讀取一行(一行))
             ^^^^^^^^^^^^^^
  File "C:\qieyun-rime-table-main\yuntu_gen.py", line 403, in 讀取一行
    小韻號, 字頭, 全部字, 反切, 編碼, \
ValueError: not enough values to unpack (expected 10, got 6)
```

**Comment by untunt** [comment]
不好意思，这是因为 `diwei_added.txt` 的内容和格式一直没有更新。现在先改成不读取 `diwei_added.txt` 的数据了，以后有机会再统一更新 `diwei_added.txt`
